# Fleur - 静态分析配置
# 基于 flutter_lints + 严格的防 bug 规则
include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    # 将特定 lint 提升为错误（构建时失败）
    missing_required_param: error
    missing_return: error
    dead_code: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"

linter:
  rules:
    # === 防止真实 Bug 的规则 ===
    # 异步编程
    - unawaited_futures
    - avoid_void_async
    - cancel_subscriptions
    - close_sinks

    # 类型安全
    - avoid_dynamic_calls
    - avoid_type_to_string
    - no_adjacent_strings_in_list

    # 逻辑错误
    - no_logic_in_create_state
    - use_build_context_synchronously
    - use_key_in_widget_constructors

    # 资源管理
    - discarded_futures

    # 代码清晰性（非风格偏好）
    - always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
    # - avoid_redundant_argument_values  # 噪音太大，禁用
    # - prefer_final_locals              # 风格偏好，禁用
    # - unnecessary_await_in_return      # 微优化，禁用
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations
